[package]
name = "rust-kimi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json="*"
serde={version="*", features=["derive"]}
serde_with="*"

tokio={version="*", features=["full"]}
reqwest = { version="*", features=["json", "multipart"]}